In [2]:
import pandas as pd

In [7]:
df_221Q_label = pd.read_excel('22_1Q.XLSX')
df_231Q_label = pd.read_excel('23_1Q.XLSX')

In [3]:
data = pd.read_csv('C:/Users/dochy/Desktop/고려대/딥러닝/project/.vscode/data.csv')

In [57]:
data

회사명       당기_유동자산      당기_비유동자산         당기_자본       당기_유동부채  \
0         3S  2.476527e+10  4.119151e+10  4.588854e+10  1.764336e+10   
1     AJ네트웍스  2.037299e+11  1.186349e+12  3.887301e+11  7.333065e+11   
2      AK홀딩스  7.548319e+10  8.567521e+11  5.510517e+11  3.811627e+11   
3        APS  5.087194e+10  2.245058e+11  1.818026e+11  7.086811e+10   
4      AP시스템  3.922670e+11  1.513681e+11  2.765309e+11  2.120491e+11   
...      ...           ...           ...           ...           ...   
2266      흥국  5.743732e+10  4.065163e+10  7.946346e+10  1.528045e+10   
2267  흥국에프엔비  4.154375e+10  1.470849e+11  8.681026e+10  3.112410e+10   
2268    흥아해운  8.189277e+10  2.196050e+11  1.373912e+11  4.865131e+10   
2269      희림  1.436306e+11  4.889646e+10  6.566610e+10  1.081137e+11   
2270      힘스  2.999778e+10  5.024690e+10  5.940935e+10  1.891705e+10   

          당기_비유동부채  당기_부채 및 자본총계       당기_부채총계       당기_자산총계      유동비율  \
0     2.424885e+09  6.595678e+10  2.006824e+10  6.595678e+10  1.403660   
1     2.680423e+11  1.390079e+12  1.001349e+12  1.390079e+12  0.277824   
2     2.081565e+07  9.322353e+11  3.811836e+11  9.322353e+11  0.198034   
3     2.270707e+10  2.753778e+11  9.357518e+10  2.753778e+11  0.717840   
4     5.505503e+10  5.436351e+11  2.671041e+11  5.436351e+11  1.849887   
...            ...           ...           ...           ...       ...   
2266  3.345051e+09  9.808896e+10  1.862550e+10  9.808896e+10  3.758877   
2267  7.069427e+10  1.886286e+11  1.018184e+11  1.886286e+11  1.334777   
2268  1.154552e+11  3.014978e+11  1.641065e+11  3.014978e+11  1.683259   
2269  1.874723e+10  1.925270e+11  1.268609e+11  1.925270e+11  1.328514   
2270  1.918279e+09  8.024468e+10  2.083533e+10  8.024468e+10  1.585753   

        자기자본비율    종목코드  
0     0.695737  060310  
1     0.279646  095570  
2     0.591108  006840  
3     0.660193  054620  
4     0.508670  265520  
...        ...     ...  
2266  0.810116  010240  
2267  0.460218  189980  
2268  0.455696  003280  
2269  0.341075  037440  
2270  0.740353  238490  

[2271 rows x 12 columns]

In [5]:
data['종목코드'] = data['종목코드'].str.replace('[', '').str.replace(']', '')

In [6]:
BS_2023_1Q = pd.merge(data,label_2, on='종목코드', how='inner')

NameError: name 'label_2' is not defined

In [70]:
BS_2023_1Q.to_csv('BS_2023_1Q.csv', index=False)

In [66]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
BS_2022_1Q = pd.read_csv('BS_2022_1Q.csv')

In [74]:
test = BS_2023_1Q.drop(['회사명', '등락률', '유동비율'], axis=1)
test.dropna(inplace=True)
X = test.drop('class', axis=1)
y = test['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [75]:
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.62


In [117]:
import torch 
import torch.nn as nn
import torch.optim as optim

In [77]:
X = test.drop('class', axis=1).values
y = test['class'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

In [187]:
class DNNModel(nn.Module):
    def __init__(self):
        super(DNNModel, self).__init__()
        
        self.fc1 = nn.Linear(10, 64)  # Adjust input size to 3
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.sigmoid(self.fc3(x))
        return x

In [128]:
# Create the DNN model
model = DNNModel()

#Define the loss function and optimizer
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train the model
epochs = 2000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train.view(-1, 1))
    loss.backward()
    optimizer.step()

# Evaluate the model on the test set
with torch.no_grad():
    y_pred = model(X_test)
    y_pred = (y_pred >= 0.5).float()  # Convert probabilities to binary predictions

    accuracy = accuracy_score(y_test.numpy(), y_pred.numpy())
    print(f'Accuracy: {accuracy:.2f}')

# 실패한 label

Accuracy: 0.54


In [24]:
# 새로운 label
df_231Q_label = pd.read_excel('23_1Q.xlsx')

c:\Users\dochy\anaconda3\envs\dl\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


In [148]:
df_231Q_label['binary_label'] = df_231Q_label['등락률'].apply(lambda x: 0 if x <= -10 else (1 if x < 0 else (2 if x < 10 else 3)))

In [149]:
df_231Q_label

종목코드      종목명  시작일 기준가  종료일 종가     대비    등락률        거래량          거래대금  \
0     060310       3S     2285    2825    540  23.63  232252042  714015009250   
1     095570   AJ네트웍스     4710    4480   -230  -4.88    6884355   31572650690   
2     006840    AK홀딩스    17880   19420   1540   8.61    1233916   24087890210   
3     054620      APS    14350    9800  -4550 -31.71   10742147  120939484360   
4     265520    AP시스템    22300   21350   -950  -4.26    5056321  107150077030   
...      ...      ...      ...     ...    ...    ...        ...           ...   
2692  000547  흥국화재2우B    19100    8050 -11050 -57.85     440278    4723837810   
2693  000545    흥국화재우     6210    5590   -620  -9.98     202548    1172893980   
2694  003280     흥아해운     1379    2170    791  57.36  187809771  384965852568   
2695  037440       희림     9120    8430   -690  -7.57   25982290  245124732060   
2696  238490       힘스     7100    7470    370   5.21   27151540  232694352500   

      class  binary_label  
0         1             3  
1         0             1  
2         1             2  
3         0             0  
4         0             1  
...     ...           ...  
2692      0             0  
2693      0             1  
2694      1             3  
2695      0             1  
2696      1             2  

[2697 rows x 10 columns]

In [174]:
len(training_df.columns)

10

In [150]:
# Assuming '종목코드' is the common column between df_data and df_label
training_df = data.merge(df_231Q_label, on='종목코드', how='inner')

In [154]:
columns_to_drop = ['회사명', '유동비율', '종목코드','종목명','시작일 기준가','종료일 종가','대비','등락률','거래량','거래대금']
training_df.drop(columns = columns_to_drop,inplace = True)

In [152]:
training_df.dropna(inplace = True)

In [156]:
del training_df['class']

In [158]:
one_hot_labels = pd.get_dummies(training_df['binary_label']).values.tolist()

In [165]:
df_encoded = pd.concat([training_df, one_hot_labels], axis=1)

# Drop the original 'class' column if needed
df_encoded.drop('binary_label', axis=1, inplace=True)

TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid

In [182]:
training_df

당기_유동자산      당기_비유동자산         당기_자본       당기_유동부채      당기_비유동부채  \
0     2.476527e+10  4.119151e+10  4.588854e+10  1.764336e+10  2.424885e+09   
1     2.037299e+11  1.186349e+12  3.887301e+11  7.333065e+11  2.680423e+11   
2     7.548319e+10  8.567521e+11  5.510517e+11  3.811627e+11  2.081565e+07   
3     5.087194e+10  2.245058e+11  1.818026e+11  7.086811e+10  2.270707e+10   
4     3.922670e+11  1.513681e+11  2.765309e+11  2.120491e+11  5.505503e+10   
...            ...           ...           ...           ...           ...   
2262  5.743732e+10  4.065163e+10  7.946346e+10  1.528045e+10  3.345051e+09   
2263  4.154375e+10  1.470849e+11  8.681026e+10  3.112410e+10  7.069427e+10   
2264  8.189277e+10  2.196050e+11  1.373912e+11  4.865131e+10  1.154552e+11   
2265  1.436306e+11  4.889646e+10  6.566610e+10  1.081137e+11  1.874723e+10   
2266  2.999778e+10  5.024690e+10  5.940935e+10  1.891705e+10  1.918279e+09   

      당기_부채 및 자본총계       당기_부채총계       당기_자산총계    자기자본비율  binary_label  
0     6.595678e+10  2.006824e+10  6.595678e+10  0.695737             3  
1     1.390079e+12  1.001349e+12  1.390079e+12  0.279646             1  
2     9.322353e+11  3.811836e+11  9.322353e+11  0.591108             2  
3     2.753778e+11  9.357518e+10  2.753778e+11  0.660193             0  
4     5.436351e+11  2.671041e+11  5.436351e+11  0.508670             1  
...            ...           ...           ...       ...           ...  
2262  9.808896e+10  1.862550e+10  9.808896e+10  0.810116             3  
2263  1.886286e+11  1.018184e+11  1.886286e+11  0.460218             2  
2264  3.014978e+11  1.641065e+11  3.014978e+11  0.455696             3  
2265  1.925270e+11  1.268609e+11  1.925270e+11  0.341075             1  
2266  8.024468e+10  2.083533e+10  8.024468e+10  0.740353             2  

[2265 rows x 10 columns]

In [168]:
X = training_df.drop('binary_label', axis=1)
y = training_df['binary_label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [181]:
model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# 실패 왜 y_pred 가 다 1?

Accuracy: 0.27


In [170]:
y_pred

array([0, 0, 2, 2, 3, 3, 3, 2, 2, 2, 2, 1, 2, 3, 3, 3, 2, 2, 3, 3, 2, 2,
       3, 2, 1, 3, 2, 2, 2, 3, 1, 3, 3, 2, 3, 1, 1, 2, 2, 3, 2, 3, 3, 0,
       2, 3, 0, 1, 2, 3, 1, 2, 2, 2, 3, 2, 3, 2, 2, 3, 2, 1, 2, 2, 2, 3,
       3, 2, 1, 2, 3, 2, 3, 3, 0, 3, 2, 0, 0, 3, 3, 3, 3, 2, 2, 2, 0, 2,
       1, 2, 2, 3, 2, 2, 2, 0, 3, 3, 3, 2, 1, 3, 2, 1, 1, 3, 1, 2, 3, 3,
       3, 2, 3, 3, 3, 2, 3, 1, 2, 3, 2, 2, 3, 2, 0, 2, 3, 3, 3, 2, 3, 3,
       2, 2, 2, 3, 0, 2, 3, 2, 3, 0, 2, 1, 2, 2, 2, 3, 2, 3, 2, 1, 0, 3,
       3, 2, 3, 3, 3, 3, 3, 0, 3, 2, 2, 3, 2, 2, 3, 3, 2, 3, 2, 1, 2, 2,
       0, 3, 2, 3, 3, 3, 3, 3, 2, 3, 1, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2,
       3, 3, 1, 1, 2, 3, 0, 3, 3, 2, 2, 1, 3, 2, 3, 1, 3, 2, 3, 3, 3, 3,
       1, 3, 2, 3, 3, 3, 2, 2, 3, 2, 0, 2, 3, 2, 2, 0, 3, 3, 2, 3, 3, 3,
       0, 2, 2, 2, 2, 2, 0, 2, 2, 3, 3, 2, 2, 3, 3, 2, 0, 3, 3, 2, 3, 2,
       3, 2, 3, 2, 2, 2, 1, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 0, 3, 2, 2, 0,

In [171]:
y_test

1757    0
1282    2
351     3
421     2
57      2
       ..
651     2
8       0
1518    1
2102    1
451     2
Name: binary_label, Length: 453, dtype: int64

In [183]:
X_train = torch.tensor(X_train.values, dtype=torch.float32)
X_test = torch.tensor(X_test.values, dtype=torch.float32)
y_train = torch.tensor(y_train.values, dtype=torch.float32)
y_test = torch.tensor(y_test.values, dtype=torch.float32)

tensor([[ 7.3896e+10,  1.5547e+11,  1.1713e+11,  ...,  1.1224e+11,
          2.2937e+11,  5.1065e-01],
        [ 2.0379e+10,  3.5564e+11,  3.0691e+11,  ...,  6.9109e+10,
          3.7602e+11,  8.1621e-01],
        [ 7.7289e+10,  5.9422e+10,  8.9467e+10,  ...,  4.7244e+10,
          1.3671e+11,  6.5442e-01],
        ...,
        [ 6.2626e+10,  6.6701e+10,  1.1093e+11,  ...,  1.8393e+10,
          1.2933e+11,  8.5778e-01],
        [ 9.1562e+09,  5.5655e+10, -3.4513e+10,  ...,  9.9324e+10,
          6.4811e+10, -5.3251e-01],
        [ 8.5293e+10,  1.2922e+11,  1.9692e+11,  ...,  1.7602e+10,
          2.1452e+11,  9.1795e-01]])

In [189]:
# # Create the DNN model
model = DNNModel()

# #Define the loss function and optimizer
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.Adam(model.parameters(), lr=0.001)

# # Train the model
epochs = 2000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train.view(-1, 1))
    loss.backward()
    optimizer.step()

#Evaluate the model on the test set
with torch.no_grad():
    y_pred = model(X_test)
    y_pred = (y_pred >= 0.5).float()  # Convert probabilities to binary predictions

accuracy = accuracy_score(y_test.numpy(), y_pred.numpy())
print(f'Accuracy: {accuracy:.2f}')

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1812x9 and 10x64)

In [134]:
sum(y_pred)

tensor([396.])